spring.application.name=ProyectoBackEnd
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/motos
spring.datasource.username=postgres
spring.datasource.password=43997777
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

